import type { DecisionLogSeed } from './types';

export const decisionLogSeed: DecisionLogSeed = {
  context: {
    project: 'The Med',
    developer: 'People & Places',
    demoMode: true,
  },

  filters: {
    dateRanges: ['Last 7 Days', 'Last 30 Days', 'This Quarter'],
    decisionTypes: ['Repricing', 'Release Strategy', 'Payment Plan', 'Portfolio Shaping'],
    statuses: [
      'Recommended',
      'Approved',
      'Rejected',
      'Overridden',
      'Executed',
      'Outcome Pending',
      'Outcome Observed',
    ],
    confidenceLevels: ['High', 'Medium', 'Low'],
  },

  rows: [
    {
      id: 'log-001',
      date: '2026-04-05',
      title: 'Aging standard-view 2BR repricing',
      scope: 'Phase 1 / D4 + E2 / 2BR + 1BR standard inventory',
      decisionType: 'Repricing',
      recommendedAction: 'Reduce price by 2.5% and shift to 8Y plan',
      finalAction: 'Awaiting Approval',
      owner: 'Commercial Director',
      confidence: 'Medium',
      status: 'Recommended',
      outcomeStatus: 'Outcome Pending',
      notes:
        'Top-ranked scenario improved revenue and reduced aging exposure while preserving premium stock.',
      linkedRecommendationId: 'rec-001',
    },
    {
      id: 'log-002',
      date: '2026-04-03',
      title: 'Pool-view 1BR conversion support',
      scope: 'Phase 1 / Pool Side / 1BR',
      decisionType: 'Payment Plan',
      recommendedAction: 'Move from 5Y / 20% DP to 8Y / 10% DP',
      finalAction: 'Approved',
      owner: 'Sales Director',
      confidence: 'Medium',
      status: 'Executed',
      outcomeStatus: 'Outcome Pending',
      notes: 'Approved as a tactical move for softening reservation velocity.',
      linkedRecommendationId: 'rec-002',
    },
    {
      id: 'log-003',
      date: '2026-04-01',
      title: 'Premium corner release acceleration',
      scope: 'Phase 1 / Sea Edge / premium corner units',
      decisionType: 'Release Strategy',
      recommendedAction: 'Release 3 premium units earlier than current phasing',
      finalAction: 'Rejected',
      owner: 'Commercial Director',
      confidence: 'Low',
      status: 'Rejected',
      outcomeStatus: 'N/A',
      notes: 'Rejected due to brand-positioning and scarcity concerns.',
      linkedRecommendationId: 'rec-003',
    },
    {
      id: 'log-004',
      date: '2026-03-30',
      title: 'Building D4 price spread normalization',
      scope: 'Phase 1 / D4 / comparable 2BR stock',
      decisionType: 'Portfolio Shaping',
      recommendedAction: 'Normalize price spread and rebalance sales priority',
      finalAction: 'Approved with override',
      owner: 'Business Analysis Lead',
      confidence: 'Medium',
      status: 'Overridden',
      outcomeStatus: 'Outcome Pending',
      notes: 'Approved but discount band narrowed from 4% to 2%.',
      linkedRecommendationId: 'rec-004',
    },
    {
      id: 'log-005',
      date: '2026-03-25',
      title: 'Lagoon-front payment plan tightening',
      scope: 'Phase 1 / B2 / Lagoon Front apartments',
      decisionType: 'Payment Plan',
      recommendedAction: 'Tighten from 8Y / 10% DP to 6Y / 15% DP',
      finalAction: 'Approved',
      owner: 'Finance Director',
      confidence: 'High',
      status: 'Outcome Observed',
      outcomeStatus: 'Observed',
      notes: 'Reservation conversion held steady while cash efficiency improved.',
      linkedRecommendationId: 'rec-005',
    },
  ],

  detailPanels: {
    'log-001': {
      rationale: [
        'Aging exceeded 75-day threshold',
        'Reservation trend weakened vs phase average',
        'Price floor still allows tactical adjustment',
        'Premium stock remains protected',
      ],
      constraintCheck: [
        { label: 'Minimum price floor', status: 'Passed' },
        { label: 'Protect premium units', status: 'Passed' },
        { label: 'Do not discount lagoon-front stock', status: 'Passed' },
      ],
      linkedWorldModelNodes: [
        'decision-repricing',
        'constraint-price-floor',
        'constraint-protect-premium',
        'signal-aging-2br',
      ],
    },
  },
};
